TIQRI.ITS.Web/Controllers/Api/AssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using TIQRI.ITS.Domain.Models;
using TIQRI.ITS.Domain.Services;
using TIQRI.ITS.Web.ViewModels;

namespace TIQRI.ITS.Web.Controllers.Api
{
    public class AssetController : ApiController
    {
        [HttpPost]
        public async Task<HttpResponseMessage> SaveAsset(AssetViewModel model)
        {
            string ApproverName = "";
            if (!String.IsNullOrEmpty(model.AssetApproveId))
            {
                ApproverName = Helpers.HRDataHelper.GetEmployee(model.AssetApproveId).Name;
            }

            var status = await new AssetService().SaveAsset(model.MapToAsset(), ApproverName ,new UserProfile()
            {
                UserName = model.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> SaveModel(AddNewDataViewModel model)
        {
            var status = await new AssetService().SaveModel(model.MapToAsset(), new UserProfile()
            {
                UserName = model.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> SaveManufacturer(AddNewDataViewModel manufacturer)
        {
            var status = await new AssetService().SaveManufacturer(manufacturer.MapToManufacturer(), new UserProfile()
            {
                UserName = manufacturer.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> SaveMemory(AddNewDataViewModel memory)
        {
            var status = await new AssetService().SaveMemory(memory.MapToMemory(), new UserProfile()
            {
                UserName = memory.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }
        [HttpPost]
        public async Task<HttpResponseMessage> SaveProcessor(AddNewDataViewModel processor)
        {
            var status = await new AssetService().SaveProcessor(processor.MapToProcessor(), new UserProfile()
            {
                UserName = processor.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> SaveHardDisk(AddNewDataViewModel hardDisk)
        {
            var status = await new AssetService().SaveHardDisk(hardDisk.MapToHardDisk(), new UserProfile()
            {
                UserName = hardDisk.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> SaveScreenSize(AddNewDataViewModel screenSize)
        {
            var status = await new AssetService().SaveScreenSize(screenSize.MapToScreenSize(), new UserProfile()
            {
                UserName = screenSize.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }
        [HttpPost]
        public async Task<HttpResponseMessage> SaveVendor(AddNewDataViewModel vendor)
        {
            var status = await new AssetService().SaveVendor(vendor.MapToVendor(), new UserProfile()
            {
                UserName = vendor.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }
        [HttpPost]
        public async Task<HttpResponseMessage> SaveLeasePeriod(AddNewDataViewModel leasePeriod)
        {
            var status = await new AssetService().SaveLeasePeriod(leasePeriod.MapToLeasePeriod(), new UserProfile()
            {
                UserName = leasePeriod.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> SaveWarrantyPeriod(AddNewDataViewModel leasePeriod)
        {
            var status = await new AssetService().SaveWarrantyPeriod(leasePeriod.MapToWarrantyPeriod(), new UserProfile()
            {
                UserName = leasePeriod.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> UpdateAssetStatusAprroval(AssetViewModel model)
        {
            var status = await new AssetService().UpdateAssetStatusAprroval(model.MapToAsset(), new UserProfile()
            {
                UserName = model.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [HttpPost]
        public async void VerifyAssetAvailability()
        {
            //var allEmployeeList = Helpers.HRDataHelper.GetBlankEmployeeList();
            //foreach(var employee in allEmployeeList)
            //{
            //var empDetalsDT = Helpers.AssetHelper.GetEmployeeProductsDetails(employee.UserName, employee.Name);
            var empDetalsDT = Helpers.AssetHelper.GetEmployeeProductsDetails("psn@tiqri.com", "Thushara Priyantha");
            //}
            string subject = "Verify Asset Availability";
            //string body = "Hi " + employee.Name +", ";
            string body = "Hi Onila Pemathunghe, ";
            body += "<br> <br> ";
            body += "According to the Asset System below item/s is/are " +
                "possessed by you. If the list is not accurate or even one " +
                "of the mentioned items is not possessed by you please let " +
                "us know immedietly to provided email below";
            body += "<br> <br> ";
            body += "<table border=1 >";
            body += "<tr>" +
                    "<th> Asset Type </th>" +
                    "<th> Manufacture </th>" +
                    "<th> Model </th>" +
                    "<th> Asset Number </th>" +
                    "<th> Manufacture serial Number </th>" +
                    "</tr>";
            for (int x = 0; x < empDetalsDT.ProductList.Count; x++)
            {
                body += "<tr>" +
                    "<td>" + empDetalsDT.ProductList[x].AssetType + "</td>" +
                    "<td>" + empDetalsDT.ProductList[x].Manufacture + "</td>" +
                    "<td>" + empDetalsDT.ProductList[x].Model + "</td>" +
                    "<td>" + empDetalsDT.ProductList[x].AssetNumber + "</td>"+
                    "<td>" + empDetalsDT.ProductList[x].ManufactureSN + "</td>";
            }
            body += "</table>";
            body += "<br> <br> ";
            body += "Email - psn@tiqri.com";
            body += "<br> <br> ";
            body += "Thanks and Regards From HR !";
            body += "<br> <br> ";
            body += "<br> <br> ";
            AssetService assetService = new AssetService();
            assetService.SendVerifyAssetDetails("psn@tiqri.com", subject, body);
            ///Thread.Sleep(5000);
        }

    }

    public class UpdateAssetStatus
    {
        public string AssetNumber { get; set; }
        public string UserId { get; set; }
        [HttpPost]
        public async Task<HttpResponseMessage> SaveAssetOwner(AddNewDataViewModel assetOwner)
        {
            var status = await new AssetService().SaveAssetOwner(assetOwner.MapToAssetOwner(), new UserProfile()
            {
                UserName = assetOwner.UserName
            });

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

    }
}

TIQRI.ITS.Web/Controllers/AssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using TIQRI.ITS.Domain.Enums;
using TIQRI.ITS.Domain.Helpers;
using TIQRI.ITS.Domain.Models;
using TIQRI.ITS.Domain.SearchQueries;
using TIQRI.ITS.Domain.Services;
using TIQRI.ITS.Web.ViewModels;
using LinqToExcel;
using System.Data;
using System.Data.Entity.Validation;
using System.Data.OleDb;
using System.IO;
using System.Security.Claims;
using System.Web;
using context = System.Web.HttpContext;
using ExcelDataReader;

namespace TIQRI.ITS.Web.Controllers
{
    public class AssetController : BaseController
    {

        string bulkUploadResult = "";
        string errorMsg = "";
        // GET: Asset
        public ActionResult Index(string assetType)
        {
            if (Session["UserName"] == null)
                return RedirectToAction("index", "home");
            if (!Helpers.SecurityHelper.IsAdminAccess(Session["UserName"].ToString()))
                return RedirectToAction("index", "home");

            return View(new AsseHomeViewModel(assetType));
        }

        public ActionResult SearchAssetList(string assetType, string searchText)
        {
            var AssetList = new AssetService().SearchAsset(new AssetSearchQuery()
            {
                GlobalText = searchText,
                AssetType = (AssetType)Enum.Parse(typeof(AssetType), assetType)
            });
            return View(AssetList);
        }


        public ActionResult BulkImportAsset(string assetType, int? id)
        {
            return View();
        }

        public FileResult DownloadExcel()
        {
            string path = "../../Content/Sample/assetBulk.xlsx";
            return File(path, "application/vnd.ms-excel", "AssetBulk.xlsx");
        }

        public FileResult DownloadBulkUploadResultsReport()
        {
            string path = "~/Content/BulkUploadStatusReport/bulkUploadResults.txt";
            return File(path, "application/vnd.ms-excel", "bulkUploadResults.txt");
        }


        [HttpPost]
        public JsonResult UploadExcel(HttpPostedFileBase FileUpload)
        {
            var assetType = Request["assetType"];
            List<string> data = new List<string>();
            string filepath = Server.MapPath("~/Content/BulkUploadStatusReport/");

            if (FileUpload != null)
            {
                // tdata.ExecuteCommand("truncate table OtherCompanyAssets");
                if (FileUpload.ContentType == "application/vnd.ms-excel" || FileUpload.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                {
                    string filename = FileUpload.FileName;
                    string targetpath = Server.MapPath("~/Content/");
                    FileUpload.SaveAs(targetpath + filename);
                    string pathToExcelFile = targetpath + filename;
                    var assetList = new List<Asset>();


                    IExcelDataReader reader = null;
                    ////Load file into a stream
                    FileStream stream = System.IO.File.Open(pathToExcelFile, FileMode.Open, FileAccess.Read);

                    if (System.IO.Path.GetExtension(pathToExcelFile).Equals(".xls"))
                    {
                        reader = ExcelReaderFactory.CreateReader(stream);
                    }
                    else if (System.IO.Path.GetExtension(pathToExcelFile).Equals(".xlsx"))
                    {
                        reader = ExcelReaderFactory.CreateReader(stream);
                    }

                    if (reader != null)
                    {
                        //Fill DataSet
                        System.Data.DataSet result = reader.AsDataSet();
                        try
                        {
                            //Loop through rows for the desired worksheet
                            //In this case I use the table index "0" to pick the first worksheet in the workbook
                            int counter = 0;
                            foreach (DataRow row in result.Tables[0].Rows)
                            {
                                if (counter == 0)
                                {
                                    counter++;
                                    continue;
                                }
                                string FirstColumn = row[0].ToString();

                                AssetType at = (AssetType)Enum.Parse(typeof(AssetType), assetType);
                                int atNo = (int)at;
                                Asset TA = new Asset();
                                TA.AssetNumber = CreateAssetNumber(at, out int? incrementNumber);
                                TA.AssetType = (AssetType)Enum.Parse(typeof(AssetType), assetType);

                                TA.Model = row[0].ToString();
                                TA.UserId = row[1].ToString();
                                if (!string.IsNullOrEmpty(row[1].ToString()))
                                {
                                    var userProfile = Helpers.HRDataHelper.GetEmployee(row[1].ToString());
                                    if (userProfile != null)
                                        TA.UserDisplayName = userProfile.Name;
                                }
                                TA.Group = row[3].ToString();
                                TA.Customer = row[4].ToString();
                                TA.Processor = row[5].ToString();
                                TA.Memory = row[6].ToString();
                                TA.Speed = row[7].ToString();
                                TA.Manufacture = row[8].ToString();
                                TA.ManufactureSN = row[9].ToString();
                                TA.ComputerName = row[10].ToString();
                                TA.MobileName = row[11].ToString();
                                if (!string.IsNullOrEmpty(row[12].ToString()))
                                {
                                    TA.Availability = (AvailabilityType)Enum.Parse(typeof(AvailabilityType), row[12].ToString());
                                }
                                TA.AssetStatus = row[13].ToString();
                                TA.AssetOwner = row[14].ToString();
                                TA.Screen = row[15].ToString();
                                TA.HDD = row[16].ToString();
                                TA.ProblemReported = Convert.ToBoolean(row[17].ToString());
                                TA.IsSSD = Convert.ToBoolean(row[18].ToString());
                                TA.Vendor = row[19].ToString();
                                TA.WarrantyPeriod = row[20].ToString();
                                TA.DeviceType = row[21].ToString();
                                TA.Cost = Convert.ToDecimal(row[22].ToString());
                                TA.DatePurchasedOrleased = Convert.ToDateTime(row[23].ToString());
                                TA.LeasePeriod = row[24].ToString();
                                TA.Location = row[25].ToString();
                                TA.ConferenceRoom = row[26].ToString();
                                TA.Building = row[27].ToString();
                                TA.Floor = row[28].ToString();
                                TA.Rating = row[29].ToString();
                                TA.NOTE = row[30].ToString();
                                TA.DateLastUpdated = DateTime.UtcNow;

                                ClaimsIdentity userClaims;
                                userClaims = User.Identity as ClaimsIdentity;
                                var claimEmail = userClaims?.FindFirst("preferred_username")?.Value;

                                TA.UserLastUpdated = claimEmail;
                                if (isValid(TA))
                                {
                                    var status = new AssetService().SaveAsset(TA, "", new UserProfile()
                                    {
                                        UserName = claimEmail
                                    });
                                    bulkUploadResult = bulkUploadResult + "Data row No " + counter + ": Success! Asset Id:" + TA.AssetNumber + "\n ";
                                }
                                else
                                {

                                    bulkUploadResult = bulkUploadResult + "Data row No " + counter + ": Failed with the error - " + errorMsg + "\r\n";
                                    //data.Add("Please choose Excel file");
                                    continue;
                                }

                                counter++;

                            }
                            try
                            {

                                if (!Directory.Exists(filepath))
                                {
                                    Directory.CreateDirectory(filepath);

                                }
                                //filepath = Request.PhysicalApplicationPath+"bulkUploadResults.txt";   //Text File Name
                                if (!System.IO.File.Exists(filepath))
                                {

                                }

                                StreamWriter sw = System.IO.File.CreateText(filepath + "bulkUploadResults.txt");
                                string error = "Adding data in line No " + counter + " was unsuccessful";
                                sw.WriteLine("-----------Bulk upload results report on " + " " + DateTime.Now.ToString() + "-----------------");
                                sw.WriteLine("-------------------------------------------------------------------------------------");
                                sw.WriteLine(bulkUploadResult);

TIQRI.ITS.Web/Views/Asset/BulkImportAsset.cshtml
@{
    Layout = null;
}

<h4>Bulk Import Assets</h4>
<hr />
@*@using (Html.BeginForm("UploadExcel", "Asset", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return myFunction()" }))
    {*@

<div class="form-group div-search-results" id="DIV_BulkUploadLoader">

                <div class="icon-spinner icon-2x icon-spin"></div>

</div>
<div id="BulkUploadFormDiv">
    <form enctype="multipart/form-data" id="excel-upload-form">
        <div class="form-horizontal">
            <div class="form-group">
                <div class="control-label col-md-2">Download Format:</div>
                <div class="col-md-10">
                    <a href="/Asset/DownloadExcel/"><img src="~/Content/images/excel.png" width="30" height="30" title="Download Excel format" alt="excel" /></a>
                    <small><b style="color:red">Caution: </b>1st row is an example, please remove it before you publish.</small>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">Excel:</div>
                <div class="col-md-10">
                    <input type="file" id="FileUpload" onchange="AssetManagement.BulkFileOnChange()" name="FileUpload" class="" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @*onclick="AssetManagement.AssetBulkUpload()"*@
                    <input type="button" onclick="AssetManagement.AssetBulkUpload()" disabled value="Upload" id="btnSubmit" class="btn btn-primary" />
                </div>
            </div>
        </div>
        <div class="form-horizontal">
            <div class="form-group" style="background-color:#0094ff">
                <div class="control-label col-md-2">Download last bulk upload results:</div>
                <div class="col-md-10">
                    <a href="/Asset/DownloadBulkUploadResultsReport"><img src="~/Content/images/ico_report.png" width="50" height="50" title="Download last bulk upload results" alt="excel" /></a>
                </div>
            </div>
        </div>
    </form>
</div>
@*}*@

TIQRI.ITS.Web/Views/Asset/Index.cshtml
@model TIQRI.ITS.Web.ViewModels.AsseHomeViewModel
@{
    Layout = null;
}
<script src="~/Scripts/Forms/asset_frm.js"></script>
<div class="container-fluid">
    <div class="side-body">
        <div class="row">
            <div class="col-xs-12">
                <input type="hidden" id="Asset_Type" value="@Model.AssetType" />
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <div class="title">
                                Manage @Model.AssetTypeDisplay
                            </div>
                            <div class="description">
                                Please use search to find specific results
                            </div>
                        </div>
                        <div class="pull-right card-action form-top-button-margin">
                            <div class="btn-group" role="group" aria-label="...">
                                <input type="button" value="Add New @Model.AssetTypeDisplay" class="btn btn-success" onclick="AssetManagement.LoadAddEditForm();" />
                            </div>
                            <div class="btn-group" role="group" aria-label="...">
                                <input type="button" value="Bulk Import" class="btn btn-success" onclick="AssetManagement.LoadBulkImportForm();" />
                            </div>
                        </div>
                    </div>

                    <div class="card-body form-horizontal">
                        <div class="row">
                            <div id="Div_PageInner_SearchPanel" class="col-sm-4 main-search-panel">
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <input type="text" id="TextBox_Asset_SearchBox" onkeyup="AssetManagement.FindAssets();"
                                               placeholder="What do you want to find ?" class="form-control main-search-box"></input>
                                    </div>
                                </div>
                                <div class="form-group div-search-results" id="DIV_AssetManagementList">
                                    <table class="clearTable" style="margin-top: 20px;">
                                        <tr>
                                            <td style="padding-left: 20px; width: 20px;">
                                                <div class="icon-spinner icon-2x icon-spin"></div>
                                            </td>
                                            <td style="padding-left: 10px;">Loading @Model.AssetTypeDisplay list. Please wait…</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <div class="col-sm-8" id="DIV_PageInner_OperationDetails">

                                <div class="select-message">
                                    <img src="../../Content/img/information.png" /><br />
                                    Please select to Edit Or Add New
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div id="DIV_AssetManagementLoadingMessage" style="display: none;">
    <table class="clearTable" style="margin-top: 20px;">
        <tr>
            <td style="padding-left: 20px; width: 20px;">
                <div class="icon-spinner icon-2x icon-spin"></div>
            </td>
            <td style="padding-left: 10px;">Loading @Model.AssetTypeDisplay list. Please wait…</td>
        </tr>
    </table>
</div>

<script>
    $(document).ready(function () {
        AssetManagement.SearchAssets();
    });

    $('#DIV_PageInner_OperationDetails').bind('heightChange', function () {
    });
</script>

TIQRI.ITS.Web/Views/Asset/SearchAssetList.cshtml
@model IList<TIQRI.ITS.Domain.Models.Asset>
@{
    Layout = null;
}

<table cellpadding="0" cellspacing="0" border="0" class="display" id="TBL_EntitySearchResults" style="width: 100%; margin-top: 10px;">

    @foreach (var item in Model)
    {
    <tr class="dataGridInnertr" onclick="AssetManagement.LoadAddEditForm(@item.Id)">
        <td class="entity-data-td">
            @if (item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.Laptop)
            {

                <div class="entity-index-item-title-large">@item.AssetNumber.ToUpper() (@item.Manufacture - @item.Model)</div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Processor</b> : @item.Processor &nbsp;&nbsp;<b>Memory</b> : @item.Memory &nbsp;&nbsp;<b>HDD</b> : @item.HDD</span> </div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Owner</b> : @item.UserId &nbsp;&nbsp;<b>SN</b> : @item.ManufactureSN</div>

            }

            @if (item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.ConferenceRoomDevice)
            {
                <div class="entity-index-item-title-large">@item.AssetNumber.ToUpper() (@item.Manufacture - @item.Model)</div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Processor</b> : @item.Processor &nbsp;&nbsp;<b>Memory</b> : @item.Memory &nbsp;&nbsp;<b>HDD</b> : @item.HDD</span> </div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Building</b> : @item.Building &nbsp;&nbsp;<b>Conference Room</b> : @item.ConferenceRoom</div>
            }
            @if (item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.Display || item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.DisplayPanel || item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.Other)
            {
                <div class="entity-index-item-title-large">@item.AssetNumber.ToUpper() (@item.Manufacture - @item.Model)</div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Floor</b> : @item.Floor &nbsp;&nbsp;<b>Availability</b> : @item.Availability</span> </div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Owner</b> : @item.UserId &nbsp;&nbsp;<b>SN</b> : @item.ManufactureSN</div>
            }
            @if (item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.KeyboardMouse || item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.PowerAdapter || item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.InventoryAsset)
            {
                <div class="entity-index-item-title-large">@item.AssetNumber.ToUpper() (@item.Manufacture - @item.Model)</div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Device Type</b> : @item.DeviceType &nbsp;&nbsp;<b>User</b> : @item.UserId &nbsp;&nbsp;<b>Room</b> : @item.ConferenceRoom</span> </div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Status</b> : @item.AssetStatus &nbsp;&nbsp;<b>SN</b> : @item.ManufactureSN</div>
            }
            @if (item.AssetType == TIQRI.ITS.Domain.Enums.AssetType.Mobile)
            {
                <div class="entity-index-item-title-large">@item.AssetNumber.ToUpper() (@item.Manufacture - @item.Model)</div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>SN</b> : @item.ManufactureSN &nbsp;&nbsp;<b>Mobile Name</b> : @item.MobileName</span> </div>
                <div style="font-size: 12px;"><span style="margin-right: 15px;"> <b>Owner</b> : @item.UserId</div>
            }
        </td>
        <td>
            @if (item.Availability == TIQRI.ITS.Domain.Enums.AvailabilityType.Disposed)
            {
                <div style="width:10px; height:10px; background-color:red; border-radius:15px;"></div>
            }
        </td>
    </tr>
    }


    @if (Model.Count == 0)
    {
        <tr>
            <td style="padding-left: 20px;">
                No records found.
            </td>
        </tr>
    }
</table>
<script>
    AssetManagement.ResetHeight();
</script>